//! Render a bundle's summary as the README's engine-throughput block.
//! The block is generated, never edited by hand; `--check` fails when the
//! block in a file differs from what the bundle renders.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result, bail};

use crate::summary::{Figure, Summary, WorkloadSummary};

pub const BEGIN: &str = "<!-- engine-throughput:begin -->";
pub const END: &str = "<!-- engine-throughput:end -->";

/// A throughput with its unit, to three significant digits.
fn rate(value: f64, unit: &str) -> String {
    let (scaled, suffix) = if value >= 1e6 {
        (value / 1e6, "M")
    } else if value >= 1e3 {
        (value / 1e3, "k")
    } else {
        (value, "")
    };
    let digits = if scaled >= 100.0 {
        0
    } else if scaled >= 10.0 {
        1
    } else {
        2
    };
    let unit = match unit {
        "txn" => "txn/s",
        "row" => "rows/s",
        "stmt" => "stmt/s",
        other => other,
    };
    format!("{scaled:.digits$}{suffix} {unit}")
}

/// An open workload is shown as its time, which is what a reader expects.
fn open_time(throughput: f64) -> String {
    let ms = 1e3 / throughput;
    if ms >= 100.0 {
        format!("{ms:.0} ms")
    } else if ms >= 1.0 {
        format!("{ms:.1} ms")
    } else {
        format!("{ms:.2} ms")
    }
}

fn cell(figure: Option<&Figure>, unit: &str) -> String {
    match figure {
        Some(Figure {
            median: Some(value),
            ..
        }) if unit == "open" => open_time(*value),
        Some(Figure {
            median: Some(value),
            ..
        }) => rate(*value, unit),
        _ => "—".to_owned(),
    }
}

fn factor(value: f64) -> String {
    if value >= 10.0 {
        format!("{value:.0}×")
    } else if value >= 1.0 {
        format!("{value:.2}×")
    } else {
        format!("{value:.3}×")
    }
}

fn ratio(value: Option<f64>) -> String {
    match value {
        Some(value) if value >= 10.0 => format!("{value:.1}"),
        Some(value) if value >= 0.01 => format!("{value:.2}"),
        Some(value) => format!("{value:.4}"),
        None => "—".to_owned(),
    }
}

/// The block for the normal pair, markers included.
pub fn block(summary: &Summary, bundle_path: &str) -> Result<String> {
    if !summary.publishable {
        bail!(
            "bundle {} is not publishable: {}",
            summary.bundle,
            summary.blockers.join("; ")
        );
    }
    let sqlite = summary
        .sqlite_version
        .clone()
        .unwrap_or_else(|| "sqlite".to_owned());
    let sqlite_name = sqlite.replacen("sqlite", "SQLite", 1);
    let newest = summary.labels.last().context("bundle has no version")?;
    let baseline = &summary.labels[0];
    let mut out = String::new();
    out.push_str(BEGIN);
    out.push('\n');
    out.push_str(&format!(
        "<!-- Generated by: `redline-scoreboard render` from {bundle_path}/summary.json; do not edit by hand. -->\n"
    ));
    let mut header = vec!["Workload".to_owned()];
    let mut align = vec!["---".to_owned()];
    for label in &summary.labels {
        header.push(label.clone());
        align.push("---:".to_owned());
    }
    if summary.labels.len() > 1 {
        header.push(format!("{newest} ÷ {baseline}"));
        align.push("---:".to_owned());
    }
    header.push(sqlite_name.clone());
    align.push("---:".to_owned());
    header.push(format!("{newest} ÷ SQLite"));
    align.push("---:".to_owned());
    out.push_str(&format!("| {} |\n", header.join(" | ")));
    out.push_str(&format!("|{}|\n", align.join("|")));

    let normal: Vec<&WorkloadSummary> = summary
        .workloads
        .iter()
        .filter(|workload| workload.pair == "normal")
        .collect();
    let mut noise = false;
    for workload in &normal {
        let mut row = vec![workload.summary.clone()];
        for label in &summary.labels {
            row.push(cell(workload.throughput.get(label), &workload.unit));
        }
        if summary.labels.len() > 1 {
            let key = format!("{newest}/{baseline}");
            row.push(match workload.speedup.get(&key) {
                Some(speedup) => match speedup.median {
                    Some(value) if speedup.exceeds_noise => factor(value),
                    Some(value) => {
                        noise = true;
                        format!("{}†", factor(value))
                    }
                    None => "—".to_owned(),
                },
                None => "—".to_owned(),
            });
        }
        row.push(cell(
            workload.throughput.get(&format!("sqlite@{newest}")),
            &workload.unit,
        ));
        row.push(ratio(workload.vs_sqlite.get(newest).and_then(|f| f.median)));
        out.push_str(&format!("| {} |\n", row.join(" | ")));
    }
    out.push('\n');
    out.push_str(&format!(
        "Throughput, higher is better, except open times. Each figure is the median of {runs} runs, \
each the median of {reps} repetitions (3 when one takes over 10 s) of the same fixed work on a \
fresh copy of a {rows}-row database, in one process, with every query on the calling thread. \
RedlineDB `Normal` durability is paired with {sqlite_name} in WAL mode with \
`synchronous=NORMAL` and `locking_mode=EXCLUSIVE`: a commit survives a process crash, not a \
power loss, and one process owns the database. Each engine has a 64 MiB page cache; SQLite \
uses 4 KiB pages and no mmap. The files are on tmpfs, so no device cost is measured. SQLite \
is measured beside the newest version in the same runs, and the last column is RedlineDB's \
throughput over that SQLite's; below 1 means SQLite is faster.",
        runs = summary.runs,
        reps = summary.reps,
        rows = summary.rows,
    ));
    if noise {
        out.push_str(" † marks a change within run-to-run noise.");
    }
    out.push_str(&format!(
        " Raw records, host and build details: [`{bundle_path}`]({bundle_path}/). \
The shell table below times whole processes, start-up included.\n"
    ));
    out.push_str(END);
    Ok(out)
}

/// Replace the block in `target`, or with `check` confirm it is current.
pub fn render_into(summary: &Summary, bundle_path: &str, target: &Path, check: bool) -> Result<()> {
    let text = fs::read_to_string(target).with_context(|| format!("read {}", target.display()))?;
    let begin = text
        .find(BEGIN)
        .with_context(|| format!("{} has no {BEGIN}", target.display()))?;
    let end = text[begin..]
        .find(END)
        .map(|at| begin + at + END.len())
        .with_context(|| format!("{} has no {END} after {BEGIN}", target.display()))?;
    let rendered = block(summary, bundle_path)?;
    if check {
        if text[begin..end] != rendered {
            bail!(
                "the engine-throughput block in {} does not match its bundle; run `redline-scoreboard render --bundle {bundle_path} --target {}`",
                target.display(),
                target.display()
            );
        }
        return Ok(());
    }
    let updated = format!("{}{}{}", &text[..begin], rendered, &text[end..]);
    fs::write(target, updated)?;
    Ok(())
}

/// The bundle a file's block was generated from, if it has one.
pub fn bundle_of(text: &str) -> Option<String> {
    let begin = text.find(BEGIN)?;
    let line = text[begin..].lines().nth(1)?;
    let from = line.find(" from ")? + " from ".len();
    let rest = &line[from..];
    let end = rest.find("/summary.json")?;
    Some(rest[..end].to_owned())
}
