//! Postgres identity columns: the sequence does not follow max(id).

use redlinedb_sql::{Connection, Database, DbOptions, SqlValue, Step};
use std::sync::Arc;
use tempfile::tempdir;

fn open() -> (tempfile::TempDir, Arc<Connection>) {
    let dir = tempdir().expect("temp dir");
    let db = Database::create(&dir.path().join("identity.db"), DbOptions::default()).expect("db");
    (dir, db.connect())
}

fn query(conn: &Arc<Connection>, sql: &str) -> Vec<Vec<SqlValue>> {
    let mut stmt = conn.prepare(sql).expect("prepare");
    let mut rows = Vec::new();
    loop {
        match stmt.step().expect("step") {
            Step::Row => {
                let mut row = Vec::with_capacity(stmt.column_count());
                for index in 0..stmt.column_count() {
                    row.push(stmt.column_value(index).expect("column").clone());
                }
                rows.push(row);
            }
            Step::Done => break,
        }
    }
    rows
}

#[test]
fn by_default_explicit_insert_does_not_advance_the_sequence() {
    let (_d, c) = open();
    c.execute("CREATE TABLE bp_idgen_bd (id int GENERATED BY DEFAULT AS IDENTITY, v text)")
        .expect("create");
    c.execute("INSERT INTO bp_idgen_bd (id, v) VALUES (100, 'manual')")
        .expect("explicit");
    let rows = query(
        &c,
        "INSERT INTO bp_idgen_bd (v) VALUES ('auto') RETURNING *",
    );
    assert_eq!(
        rows,
        vec![vec![
            SqlValue::Integer(1),
            SqlValue::Text(Arc::from("auto"))
        ]]
    );
}

#[test]
fn always_identity_honors_start_and_increment() {
    let (_d, c) = open();
    c.execute(
        "CREATE TABLE bp_idgen_restart (id int GENERATED ALWAYS AS IDENTITY (START WITH 1000 INCREMENT BY 10), v text)",
    )
    .expect("create");
    let rows = query(
        &c,
        "INSERT INTO bp_idgen_restart (v) VALUES ('a'),('b'),('c') RETURNING *",
    );
    assert_eq!(
        rows,
        vec![
            vec![SqlValue::Integer(1000), SqlValue::Text(Arc::from("a"))],
            vec![SqlValue::Integer(1010), SqlValue::Text(Arc::from("b"))],
            vec![SqlValue::Integer(1020), SqlValue::Text(Arc::from("c"))],
        ]
    );
}

#[test]
fn always_identity_accepts_overriding_system_value() {
    let (_d, c) = open();
    c.execute("CREATE TABLE osv_t (id int GENERATED ALWAYS AS IDENTITY, label text)")
        .expect("create");
    c.execute("INSERT INTO osv_t (id, label) OVERRIDING SYSTEM VALUE VALUES (42, 'forced')")
        .expect("override");
    let rows = query(&c, "SELECT id, label FROM osv_t ORDER BY id");
    assert_eq!(
        rows,
        vec![vec![
            SqlValue::Integer(42),
            SqlValue::Text(Arc::from("forced"))
        ]]
    );
}

#[test]
fn always_identity_rejects_an_explicit_value() {
    let (_d, c) = open();
    c.execute("CREATE TABLE gba_t (id int GENERATED ALWAYS AS IDENTITY, label text)")
        .expect("create");
    let err = c
        .execute("INSERT INTO gba_t (id, label) VALUES (5, 'x')")
        .expect_err("explicit always");
    let text = err.to_string();
    assert!(text.contains("cannot insert a non-DEFAULT value"), "{text}");
}

#[test]
fn alter_add_identity_fills_omitted_ids() {
    let (_d, c) = open();
    c.execute("CREATE TABLE mig_add_identity (id int NOT NULL, name text)")
        .expect("create");
    c.execute("ALTER TABLE mig_add_identity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
        .expect("add identity");
    c.execute("INSERT INTO mig_add_identity (name) VALUES ('a'),('b')")
        .expect("insert");
    let rows = query(&c, "SELECT id, name FROM mig_add_identity ORDER BY id");
    assert_eq!(
        rows,
        vec![
            vec![SqlValue::Integer(1), SqlValue::Text(Arc::from("a"))],
            vec![SqlValue::Integer(2), SqlValue::Text(Arc::from("b"))],
        ]
    );
}
