/*
 * Generated by: hand-authored C ABI surface tracked in
 *   docs/exceptions/ffi-c-header.md
 * DO NOT EDIT without updating Rust modules under crates/ffi/src in lockstep and
 * re-running `rtk cargo test -p redlinedb-ffi --quiet --locked`.
 * Source of truth: crates/ffi/src/lib.rs and its submodules.
 * Regeneration command: see docs/exceptions/ffi-c-header.md
 */
#ifndef REDLINEDB_H
#define REDLINEDB_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ABI major version. The shared library carries it in its name and identity:
 * libredlinedb.so.5 (ELF soname) and @rpath/libredlinedb.5.dylib (Mach-O
 * install name). crates/ffi/build.rs and the packaging scripts read this
 * line; change it only together with an incompatible ABI change. */
#define RLDB_ABI_MAJOR 5

typedef struct rldb rldb;
typedef struct rldb_stmt rldb_stmt;
typedef struct rldb_backup rldb_backup;
typedef rldb sqlite3;
typedef rldb_stmt sqlite3_stmt;
typedef rldb_backup sqlite3_backup;

#define RLDB_OK 0
#define RLDB_ERROR 1
#define RLDB_INTERNAL 2
#define RLDB_BUSY 5
#define RLDB_LOCKED 6
#define RLDB_NOMEM 7
#define RLDB_READONLY 8
#define RLDB_INTERRUPT 9
#define RLDB_IOERR 10
#define RLDB_CORRUPT 11
#define RLDB_SCHEMA 17
#define RLDB_TOOBIG 18
#define RLDB_CONSTRAINT 19
#define RLDB_MISMATCH 20
#define RLDB_MISUSE 21
#define RLDB_RANGE 25
#define RLDB_NOTADB 26
#define RLDB_ROW 100
#define RLDB_DONE 101

#define SQLITE_OK 0
#define SQLITE_ERROR 1
#define SQLITE_INTERNAL 2
#define SQLITE_BUSY 5
#define SQLITE_LOCKED 6
#define SQLITE_NOMEM 7
#define SQLITE_READONLY 8
#define SQLITE_INTERRUPT 9
#define SQLITE_IOERR 10
#define SQLITE_CORRUPT 11
#define SQLITE_CANTOPEN 14
#define SQLITE_SCHEMA 17
#define SQLITE_TOOBIG 18
#define SQLITE_CONSTRAINT 19
#define SQLITE_MISMATCH 20
#define SQLITE_MISUSE 21
#define SQLITE_RANGE 25
#define SQLITE_NOTADB 26
#define SQLITE_ROW 100
#define SQLITE_DONE 101

/* Native storage classes returned by rldb_column_type. */
#define RLDB_NULL 0
#define RLDB_INTEGER 1
#define RLDB_REAL 2
#define RLDB_TEXT 3
#define RLDB_BLOB 4

/* SQLite storage classes returned by sqlite3_column_type, sqlite3_value_type
 * and sqlite3_value_numeric_type. ABI v5: SQLITE_NULL is 5 as upstream
 * (v4 headers defined it as 0). */
#define SQLITE_INTEGER 1
#define SQLITE_FLOAT 2
#define SQLITE_TEXT 3
#define SQLITE_BLOB 4
#define SQLITE_NULL 5

/* ":memory:" (or SQLITE_OPEN_MEMORY) opens a private ephemeral database whose
 * filename is reported as "". URI filenames are not interpreted: with
 * SQLITE_OPEN_URI a "file:" name fails with SQLITE_CANTOPEN; without it the
 * name is a plain path. */
#define SQLITE_OPEN_READONLY 0x00000001
#define SQLITE_OPEN_READWRITE 0x00000002
#define SQLITE_OPEN_CREATE 0x00000004
#define SQLITE_OPEN_URI 0x00000040
#define SQLITE_OPEN_MEMORY 0x00000080

/* sqlite3_prepare_v3 flags. Only PERSISTENT (an allocation hint) and
 * NORMALIZE (a no-op upstream) are accepted; any other flag returns
 * SQLITE_ERROR with a NULL statement. */
#define SQLITE_PREPARE_PERSISTENT 0x01
#define SQLITE_PREPARE_NORMALIZE 0x02
#define SQLITE_PREPARE_NO_VTAB 0x04
#define SQLITE_PREPARE_DONT_LOG 0x10
#define SQLITE_PREPARE_FROM_DDL 0x20

typedef struct rldb_config {
    uint32_t struct_size;
    uint32_t flags;
    uint32_t durability;
    uint64_t cache_bytes;
    uint64_t work_mem_bytes;
    uint64_t max_spill_bytes;
    uint32_t statement_cache_capacity;
    uint32_t busy_timeout_ms;
} rldb_config;

int rldb_open(const char *path, rldb **out_db);
int rldb_open_v2(const char *path, const rldb_config *config, rldb **out_db);
int rldb_close(rldb *db);
int rldb_close_v2(rldb *db);
const char *sqlite3_libversion(void);
int sqlite3_libversion_number(void);
const char *sqlite3_sourceid(void);
int sqlite3_threadsafe(void);
const char *sqlite3_errstr(int code);

/* nbytes < 0 reads through the first NUL; nbytes >= 0 reads at most nbytes
 * bytes and still stops at the first NUL. *out_stmt is NULL on failure and
 * for blank or comment-only input. */
int rldb_prepare_v2(rldb *db, const char *sql, int nbytes, rldb_stmt **out_stmt, const char **tail);
/* ABI v5: upstream argument order (v4 took flags last as int). */
int sqlite3_prepare_v3(sqlite3 *db, const char *sql, int nbytes, unsigned int prepFlags, sqlite3_stmt **out_stmt, const char **tail);
int rldb_step(rldb_stmt *stmt);
int rldb_reset(rldb_stmt *stmt);
int rldb_finalize(rldb_stmt *stmt);
int rldb_clear_bindings(rldb_stmt *stmt);
int sqlite3_stmt_readonly(sqlite3_stmt *stmt);
int sqlite3_stmt_busy(sqlite3_stmt *stmt);
const char *sqlite3_sql(sqlite3_stmt *stmt);

int rldb_bind_null(rldb_stmt *stmt, int index);
int rldb_bind_int64(rldb_stmt *stmt, int index, int64_t value);
int rldb_bind_double(rldb_stmt *stmt, int index, double value);
int rldb_bind_text(rldb_stmt *stmt, int index, const char *value, int nbytes);
int rldb_bind_blob(rldb_stmt *stmt, int index, const void *value, int nbytes);

int rldb_parameter_count(rldb_stmt *stmt);
int rldb_bind_parameter_index(rldb_stmt *stmt, const char *name);

/* column_type reports the stored class and never changes after a conversion.
 * column_text returns INTEGER and REAL as their CAST(x AS TEXT) text, TEXT and
 * BLOB as their bytes (interior NULs kept, NUL-terminated) and NULL as a NULL
 * pointer; column_bytes is that text's length (the blob length for BLOB, 0 for
 * NULL). The pointer stays valid until the next step, reset or finalize. */
int rldb_column_count(rldb_stmt *stmt);
const char *rldb_column_name(rldb_stmt *stmt, int index);
int rldb_column_type(rldb_stmt *stmt, int index);
int64_t rldb_column_int64(rldb_stmt *stmt, int index);
double rldb_column_double(rldb_stmt *stmt, int index);
const unsigned char *rldb_column_text(rldb_stmt *stmt, int index);
const void *rldb_column_blob(rldb_stmt *stmt, int index);
int rldb_column_bytes(rldb_stmt *stmt, int index);

typedef int (*rldb_exec_callback)(void *, int, char **, char **);
/*
 * Negative-test proofs for the rldb_exec input boundary (HLT-023-INPUT-
 * BOUNDARY-GAP, Section E) live in crates/ffi/tests/exec_input_boundary.rs
 * and crates/ffi/tests/safety_invariants.rs (Section D1). See
 * .jankurai/security-policy.toml for the proof routing.
 */
int rldb_exec(rldb *db, const char *sql, rldb_exec_callback callback, void *ctx, char **errmsg);

int rldb_errcode(rldb *db);
const char *rldb_errmsg(rldb *db);
void rldb_free(void *ptr);
void rldb_interrupt(rldb *db);
int rldb_busy_timeout(rldb *db, int milliseconds);
int rldb_changes(rldb *db);
int64_t rldb_last_insert_rowid(rldb *db);

int rldb_checkpoint(rldb *db);
int rldb_vacuum(rldb *db);
int rldb_stats_json(rldb *db, char **out_json);

int rldb_backup_init(rldb *src, const char *dst_path, const rldb_config *dst_config, rldb_backup **out);
int rldb_backup_step(rldb_backup *backup, int batches);
int rldb_backup_finish(rldb_backup *backup);
int rldb_backup_close(rldb_backup *backup);
int rldb_backup_remaining(rldb_backup *backup);
int rldb_backup_pagecount(rldb_backup *backup);

typedef int (*sqlite3_exec_callback)(void *, int, char **, char **);
int sqlite3_open(const char *path, sqlite3 **out_db);
int sqlite3_open_v2(const char *path, sqlite3 **out_db, int flags, const char *vfs);
int sqlite3_close(sqlite3 *db);
int sqlite3_close_v2(sqlite3 *db);

int sqlite3_prepare_v2(sqlite3 *db, const char *sql, int nbytes, sqlite3_stmt **out_stmt, const char **tail);
int sqlite3_step(sqlite3_stmt *stmt);
int sqlite3_reset(sqlite3_stmt *stmt);
int sqlite3_finalize(sqlite3_stmt *stmt);
int sqlite3_clear_bindings(sqlite3_stmt *stmt);

int sqlite3_bind_null(sqlite3_stmt *stmt, int index);
int sqlite3_bind_int64(sqlite3_stmt *stmt, int index, int64_t value);
int sqlite3_bind_double(sqlite3_stmt *stmt, int index, double value);
int sqlite3_bind_text(sqlite3_stmt *stmt, int index, const char *value, int nbytes, void (*destructor)(void *));
int sqlite3_bind_blob(sqlite3_stmt *stmt, int index, const void *value, int nbytes, void (*destructor)(void *));

int sqlite3_parameter_count(sqlite3_stmt *stmt);
int sqlite3_bind_parameter_index(sqlite3_stmt *stmt, const char *name);

int sqlite3_column_count(sqlite3_stmt *stmt);
const char *sqlite3_column_name(sqlite3_stmt *stmt, int index);
int sqlite3_column_type(sqlite3_stmt *stmt, int index);
int64_t sqlite3_column_int64(sqlite3_stmt *stmt, int index);
double sqlite3_column_double(sqlite3_stmt *stmt, int index);
const unsigned char *sqlite3_column_text(sqlite3_stmt *stmt, int index);
const void *sqlite3_column_blob(sqlite3_stmt *stmt, int index);
int sqlite3_column_bytes(sqlite3_stmt *stmt, int index);

int sqlite3_exec(sqlite3 *db, const char *sql, sqlite3_exec_callback callback, void *ctx, char **errmsg);

int sqlite3_errcode(sqlite3 *db);
const char *sqlite3_errmsg(sqlite3 *db);
void sqlite3_free(void *ptr);
void sqlite3_interrupt(sqlite3 *db);
int sqlite3_busy_timeout(sqlite3 *db, int milliseconds);
int sqlite3_extended_result_codes(sqlite3 *db, int onoff);
int sqlite3_changes(sqlite3 *db);
int64_t sqlite3_changes64(sqlite3 *db);
int sqlite3_total_changes(sqlite3 *db);
int64_t sqlite3_total_changes64(sqlite3 *db);
int sqlite3_get_autocommit(sqlite3 *db);
int64_t sqlite3_last_insert_rowid(sqlite3 *db);
sqlite3 *sqlite3_db_handle(sqlite3_stmt *stmt);
const char *sqlite3_db_filename(sqlite3 *db, const char *name);
int sqlite3_db_readonly(sqlite3 *db, const char *name);
int sqlite3_checkpoint(sqlite3 *db);
int sqlite3_vacuum(sqlite3 *db);
int sqlite3_stats_json(sqlite3 *db, char **out_json);

/* ---- B1 value / result / context family (UDF callback ABI) ----------- */
typedef struct RldbValue sqlite3_value;
typedef struct RldbContext sqlite3_context;

int sqlite3_value_type(sqlite3_value *value);
int sqlite3_value_int(sqlite3_value *value);
int64_t sqlite3_value_int64(sqlite3_value *value);
double sqlite3_value_double(sqlite3_value *value);
const unsigned char *sqlite3_value_text(sqlite3_value *value);
const void *sqlite3_value_blob(sqlite3_value *value);
int sqlite3_value_bytes(sqlite3_value *value);

void sqlite3_result_int(sqlite3_context *ctx, int value);
void sqlite3_result_int64(sqlite3_context *ctx, int64_t value);
void sqlite3_result_double(sqlite3_context *ctx, double value);
void sqlite3_result_text(sqlite3_context *ctx, const char *text, int nbytes, void (*destructor)(void *));
void sqlite3_result_blob(sqlite3_context *ctx, const void *data, int nbytes, void (*destructor)(void *));
void sqlite3_result_null(sqlite3_context *ctx);
void sqlite3_result_error(sqlite3_context *ctx, const char *msg, int nbytes);
void sqlite3_result_error_code(sqlite3_context *ctx, int code);

sqlite3 *sqlite3_context_db_handle(sqlite3_context *ctx);
void *sqlite3_user_data(sqlite3_context *ctx);

/* ---- B2 UDF + collation registration --------------------------------- */
typedef void (*sqlite3_scalar_fn)(sqlite3_context *ctx, int argc, sqlite3_value **argv);
typedef void (*sqlite3_step_fn)(sqlite3_context *ctx, int argc, sqlite3_value **argv);
typedef void (*sqlite3_final_fn)(sqlite3_context *ctx);
typedef void (*sqlite3_destroy_fn)(void *user_data);

int sqlite3_create_function(
    sqlite3 *db,
    const char *name,
    int narg,
    int enc,
    void *user_data,
    sqlite3_scalar_fn func,
    sqlite3_step_fn step,
    sqlite3_final_fn final_func
);
int sqlite3_create_function_v2(
    sqlite3 *db,
    const char *name,
    int narg,
    int enc,
    void *user_data,
    sqlite3_scalar_fn func,
    sqlite3_step_fn step,
    sqlite3_final_fn final_func,
    sqlite3_destroy_fn destroy
);
int sqlite3_create_function16(
    sqlite3 *db,
    const void *name_utf16,
    int narg,
    int enc,
    void *user_data,
    sqlite3_scalar_fn func,
    sqlite3_step_fn step,
    sqlite3_final_fn final_func
);

typedef int (*sqlite3_collation_fn)(void *user_data, int na, const void *a, int nb, const void *b);
typedef void (*sqlite3_collation_needed_fn)(void *user_data, sqlite3 *db, int encoding, const char *name);

int sqlite3_create_collation(
    sqlite3 *db,
    const char *name,
    int enc,
    void *user_data,
    sqlite3_collation_fn compare
);
int sqlite3_create_collation_v2(
    sqlite3 *db,
    const char *name,
    int enc,
    void *user_data,
    sqlite3_collation_fn compare,
    sqlite3_destroy_fn destroy
);
int sqlite3_collation_needed(sqlite3 *db, void *user_data, sqlite3_collation_needed_fn cb);

/* ---- B3 blob I/O API ------------------------------------------------- */
typedef struct RldbBlob sqlite3_blob;

int sqlite3_blob_open(
    sqlite3 *db,
    const char *database,
    const char *table,
    const char *column,
    int64_t rowid,
    int flags,
    sqlite3_blob **out
);
int sqlite3_blob_read(sqlite3_blob *blob, void *buf, int nbytes, int offset);
int sqlite3_blob_write(sqlite3_blob *blob, const void *buf, int nbytes, int offset);
int sqlite3_blob_close(sqlite3_blob *blob);
int sqlite3_blob_reopen(sqlite3_blob *blob, int64_t rowid);
int sqlite3_blob_bytes(sqlite3_blob *blob);

/* ---- B4 hooks + busy handler + authorizer ---------------------------- */
typedef int (*sqlite3_commit_hook_fn)(void *user_data);
typedef void (*sqlite3_rollback_hook_fn)(void *user_data);
typedef void (*sqlite3_update_hook_fn)(
    void *user_data,
    int op,
    const char *db_name,
    const char *table,
    int64_t rowid
);
typedef void (*sqlite3_trace_fn)(void *user_data, const char *sql);
typedef void (*sqlite3_profile_fn)(void *user_data, const char *sql, uint64_t nanoseconds);
typedef int (*sqlite3_busy_handler_fn)(void *user_data, int attempts);
typedef int (*sqlite3_authorizer_fn)(
    void *user_data,
    int action,
    const char *arg3,
    const char *arg4,
    const char *arg5,
    const char *arg6
);

void *sqlite3_commit_hook(sqlite3 *db, sqlite3_commit_hook_fn cb, void *user_data);
void *sqlite3_rollback_hook(sqlite3 *db, sqlite3_rollback_hook_fn cb, void *user_data);
void *sqlite3_update_hook(sqlite3 *db, sqlite3_update_hook_fn cb, void *user_data);
void *sqlite3_trace(sqlite3 *db, sqlite3_trace_fn cb, void *user_data);
void *sqlite3_profile(sqlite3 *db, sqlite3_profile_fn cb, void *user_data);
int sqlite3_busy_handler(sqlite3 *db, sqlite3_busy_handler_fn cb, void *user_data);
int sqlite3_set_authorizer(sqlite3 *db, sqlite3_authorizer_fn cb, void *user_data);

#ifdef __cplusplus
}
#endif

#endif
