use std::{
    fs,
    path::PathBuf,
    process::Command,
    sync::atomic::{AtomicUsize, Ordering},
};

static NEXT: AtomicUsize = AtomicUsize::new(0);

const CANONICAL: &str = "https://github.com/neverhuman/redline";

// The retired repository, split so this source passes the scan it tests.
fn legacy_url() -> String {
    ["https://github.com/neverhuman/", "Redline", "DB.git"].concat()
}

struct Checkout(PathBuf);

impl Checkout {
    fn new() -> Self {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
        let fixtures = root.join("target/github-authority-fixtures");
        fs::create_dir_all(&fixtures).unwrap();
        let path = fixtures.join(format!(
            "redline-authority-{}-{}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        ));
        fs::create_dir(&path).unwrap();
        fs::copy(root.join("subrepos.toml"), path.join("subrepos.toml")).unwrap();
        fs::create_dir(path.join("crates")).unwrap();
        for relative in [
            ".",
            "subrepos/redline-testing",
            "subrepos/redline-web",
            "subrepos/redline-central",
            "subrepos/redline-split-ops",
            "subrepos/redline",
        ] {
            let component = path.join(relative);
            fs::create_dir_all(&component).unwrap();
            fs::write(component.join("Cargo.toml"), "[workspace]\nmembers=[]\n").unwrap();
        }
        Self(path)
    }

    fn run(&self, args: &[&str]) -> std::process::Output {
        Command::new(env!("CARGO_BIN_EXE_redline-proof"))
            .current_dir(&self.0)
            .env("REDLINE_REPO_ROOT", &self.0)
            .args(args)
            .output()
            .unwrap()
    }

    fn git(&self, args: &[&str]) {
        let status = Command::new("git")
            .arg("-C")
            .arg(&self.0)
            .args(args)
            .status()
            .unwrap();
        assert!(status.success());
    }
}

impl Drop for Checkout {
    fn drop(&mut self) {
        // This fixture contains only synthetic manifests generated by this test.
        fs::remove_dir_all(&self.0).unwrap();
    }
}

#[test]
fn complete_source_archive_validates_without_network_or_git() {
    let checkout = Checkout::new();
    let output = checkout.run(&["validate"]);
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    let report: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(report["repository"], CANONICAL);
}

#[test]
fn wrong_owner_fetch_or_push_remote_is_rejected() {
    let checkout = Checkout::new();
    checkout.git(&["init", "--quiet"]);
    checkout.git(&["remote", "add", "origin", &format!("{CANONICAL}.git")]);
    assert!(checkout.run(&["validate"]).status.success());
    checkout.git(&[
        "remote",
        "set-url",
        "--push",
        "origin",
        "https://github.com/another-owner/redline.git",
    ]);
    let output = checkout.run(&["validate"]);
    assert!(!output.status.success());
    assert!(String::from_utf8_lossy(&output.stderr).contains("remote origin must use"));
    checkout.git(&[
        "remote",
        "set-url",
        "--push",
        "origin",
        &format!("{CANONICAL}.git"),
    ]);
    checkout.git(&[
        "remote",
        "add",
        "alternate",
        "https://github.com/another-owner/redline.git",
    ]);
    assert!(!checkout.run(&["validate"]).status.success());
}

#[test]
fn retired_repository_remote_is_rejected() {
    let checkout = Checkout::new();
    checkout.git(&["init", "--quiet"]);
    checkout.git(&["remote", "add", "origin", &format!("{CANONICAL}.git")]);
    assert!(checkout.run(&["validate"]).status.success());
    checkout.git(&["remote", "add", "origin-disabled", &legacy_url()]);
    let output = checkout.run(&["validate"]);
    assert!(!output.status.success());
    assert!(String::from_utf8_lossy(&output.stderr)
        .contains(&format!("remote origin-disabled must use {CANONICAL};")));
}

#[test]
fn active_files_cannot_reintroduce_the_retired_repository() {
    let checkout = Checkout::new();
    for (relative, text) in [
        (
            "subrepos/redline/AGENTS.md",
            format!("Historical hub of {}\n", legacy_url()),
        ),
        (
            "tips/phases/plan.toml",
            format!("repository = \"{}\"\n", legacy_url()),
        ),
        (
            "docs/migration/README.md",
            format!("Imported from {}\n", legacy_url()),
        ),
        (
            "PLANNING.md",
            format!("Planning note that quotes {}\n", legacy_url()),
        ),
    ] {
        let path = checkout.0.join(relative);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, text).unwrap();
    }
    let output = checkout.run(&["validate"]);
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    for relative in [
        "subrepos/redline-testing/AGENTS.md",
        "ops/ci/lib.sh",
        "subrepos.toml",
        "README.md",
        "docs/manual/02-start-here.md",
        "subrepos/redline-web/docs/release.md",
        "subrepos/redline-central/README.md",
    ] {
        let checkout = Checkout::new();
        let path = checkout.0.join(relative);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        let mut text = fs::read_to_string(&path).unwrap_or_default();
        text.push_str(&format!("# {}\n", legacy_url().to_lowercase()));
        fs::write(&path, text).unwrap();
        let output = checkout.run(&["validate"]);
        assert!(!output.status.success(), "{relative}");
        assert!(
            String::from_utf8_lossy(&output.stderr).contains(relative),
            "{relative}: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
}

#[test]
fn retired_pipeline_and_policy_cannot_be_reactivated() {
    let checkout = Checkout::new();
    fs::write(checkout.0.join(".gitlab-ci.yml"), "stages: [test]\n").unwrap();
    assert!(!checkout.run(&["validate"]).status.success());
    fs::remove_file(checkout.0.join(".gitlab-ci.yml")).unwrap();
    fs::create_dir(checkout.0.join(".jeryu")).unwrap();
    assert!(!checkout.run(&["validate"]).status.success());
}

#[test]
fn included_component_cannot_reintroduce_an_old_forge_route() {
    let checkout = Checkout::new();
    fs::write(
        checkout.0.join("subrepos/redline-web/install.sh"),
        ["git clone https://git.neverhuman", ".org/repo.git\n"].concat(),
    )
    .unwrap();
    let output = checkout.run(&["validate"]);
    assert!(!output.status.success());
    assert!(String::from_utf8_lossy(&output.stderr).contains("subrepos/redline-web/install.sh"));
}

#[test]
fn split_publication_commands_have_no_fallback() {
    let checkout = Checkout::new();
    for command in [
        "clone",
        "update",
        "proof-refresh",
        "cutover-verify",
        "remote-verify",
    ] {
        let output = checkout.run(&[command]);
        assert!(!output.status.success(), "{command}");
        assert!(String::from_utf8_lossy(&output.stderr)
            .contains("historical consumer promotion is not supported"));
    }
}

#[test]
fn incomplete_installed_context_cannot_select_legacy_transport() {
    let checkout = Checkout::new();
    fs::remove_file(checkout.0.join("subrepos.toml")).unwrap();
    let output = checkout.run(&["doctor"]);
    assert!(!output.status.success());
    assert!(
        String::from_utf8_lossy(&output.stderr).contains(&format!("complete {CANONICAL} checkout"))
    );
}
