//! The shared styled SVG renderer, and the copy of the beyond-SQLite
//! feature-progress plot.

use std::path::PathBuf;

use crate::report::svg::{build_svg_artifacts, render_styled_svg};
use crate::report::types::{ReportOptions, SummaryJson, SvgBar, SvgMetric, SvgSpec};

#[test]
fn styled_svg_renderer_is_shared_and_suite_aware() {
    let svg = render_styled_svg(&SvgSpec {
        title: "Beyond-SQLite feature progress".to_owned(),
        subtitle: "Coverage evidence for the backlog.".to_owned(),
        accent: "#f59e0b",
        metrics: vec![SvgMetric {
            label: "Coverage".to_owned(),
            value: "33.33%".to_owned(),
        }],
        bars: vec![SvgBar {
            label: "passed".to_owned(),
            value: 4.0,
            value_label: "4".to_owned(),
        }],
    });
    assert!(svg.contains("<svg xmlns=\"http://www.w3.org/2000/svg\""));
    assert!(svg.contains("Beyond-SQLite feature progress"));
    assert!(svg.contains("Inter,Segoe UI,sans-serif"));
    assert!(svg.contains("generated by redline-testing"));
    assert!(svg.contains("fill=\"#f59e0b\""));
    assert!(svg.contains("passed"));
}

#[test]
fn beyond_sqlite_plot_uses_feature_progress_copy() {
    let summary = SummaryJson {
        suite: "beyond_sqlite".to_owned(),
        total_cases: 4,
        passed_cases: 2,
        failed_cases: 0,
        skipped_cases: 2,
        elapsed_ns: None,
        measured_samples: 2,
        warmup_samples: 0,
        ranked_cases: 2,
        repetitions: 1,
        warmup: 0,
        measurement_boundary: "cli_case_wall_time".to_owned(),
        ranked_schema: "redline-testing-ranked-v2".to_owned(),
    };
    let artifacts = build_svg_artifacts(
        &summary,
        &[],
        &[],
        &ReportOptions {
            suite: "beyond_sqlite".to_owned(),
            input: PathBuf::from("input.jsonl"),
            official_evidence: Some(PathBuf::from("official-evidence.json")),
            run_provenance: None,
            historical_run: true,
            local_diagnostics: true,
            out_dir: PathBuf::from("out"),
            readme: PathBuf::from("README.md"),
            plot: Some(PathBuf::from("feature-progress.svg")),
            performance_histogram_plot: None,
            median_test_performance_plot: None,
            readme_latency: true,
            jankurai_score: None,
            updated_date: "2026-05-24".to_owned(),
            expected_repetitions: None,
            expected_warmup: None,
            check: false,
            case_manifest: None,
        },
    );
    assert_eq!(artifacts.len(), 1);
    assert!(artifacts[0].contents.contains("feature progress"));
    assert!(
        artifacts[0]
            .contents
            .contains("Coverage evidence for the beyond-SQLite backlog.")
    );
}
