use std::collections::BTreeMap;

use anyhow::{Context, Result};

use super::evidence::{
    memory_peak_summary, memory_status_summary, suite_display_name, suite_subject,
};
use super::ratio::{format_ratio, summarize};
use super::types::{EvidenceVersions, RankedCase, RawRecord, ReportOptions, SummaryJson};
use super::utils::{csv, is_measured, median};
use crate::latency::{
    CaseLatency, MEASUREMENT_BOUNDARY, MEASUREMENT_BOUNDARY_TEXT, RANKED_CSV_HEADER,
};

pub(crate) fn parse_raw_records(raw_text: &str) -> Result<Vec<RawRecord>> {
    let mut records = Vec::new();
    for (index, line) in raw_text.lines().enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        records.push(
            serde_json::from_str(line)
                .with_context(|| format!("parse raw JSONL line {}", index.saturating_add(1)))?,
        );
    }
    Ok(records)
}

/// Per-case medians and latency ratios, slowest relative to SQLite first.
///
/// A measured case with a zero median on either side is an error: a missing
/// timing must never turn into a ratio, let alone a win.
pub(crate) fn rank_cases(records: &[RawRecord]) -> Result<Vec<RankedCase>> {
    let mut grouped = BTreeMap::<String, Vec<&RawRecord>>::new();
    for record in records.iter().filter(|record| is_measured(record)) {
        grouped
            .entry(record.case_id.clone())
            .or_default()
            .push(record);
    }
    let mut ranked = Vec::new();
    for (case_id, group) in grouped {
        let first = group[0];
        let sqlite_median_ns = median(group.iter().map(|record| record.reference_elapsed_ns));
        let redline_median_ns = median(group.iter().map(|record| record.target_elapsed_ns));
        let latency = CaseLatency::from_medians(sqlite_median_ns, redline_median_ns)
            .with_context(|| format!("rank case {case_id}"))?;
        ranked.push(RankedCase {
            case_id,
            name: first.name.clone(),
            case_file: first.case_file.clone(),
            priority: first.priority.clone(),
            profile: first.profile.clone(),
            category: first.category.clone(),
            sqlite_median_ns,
            redline_median_ns,
            latency_ratio: latency.latency_ratio,
            gap_pct: latency.gap_pct,
            below_resolution: latency.below_resolution,
            faster: latency.faster,
            samples: group.len(),
        });
    }
    ranked.sort_by(|left, right| {
        right
            .latency_ratio
            .total_cmp(&left.latency_ratio)
            .then_with(|| left.case_id.cmp(&right.case_id))
    });
    Ok(ranked)
}

pub(crate) fn ranked_csv(ranked: &[RankedCase]) -> String {
    let mut out = String::from(RANKED_CSV_HEADER);
    for (index, row) in ranked.iter().enumerate() {
        out.push_str(&format!(
            "{},{},{},{},{},{},{},{},{},{:.6},{:.6},{},{}\n",
            index.saturating_add(1),
            row.case_id,
            csv(&row.name),
            csv(&row.case_file),
            row.priority,
            row.profile,
            csv(&row.category),
            row.sqlite_median_ns,
            row.redline_median_ns,
            row.latency_ratio,
            row.gap_pct,
            row.below_resolution,
            row.samples
        ));
    }
    out
}

pub(crate) fn ksloc_csv() -> String {
    "# Generated by: redline-testing report\ncrate,loc\nredline-testing,1\n".to_owned()
}

pub(crate) fn render_report_block(
    summary: &SummaryJson,
    ranked: &[RankedCase],
    raw_records: &[RawRecord],
    options: &ReportOptions,
    evidence_versions: Option<&EvidenceVersions>,
) -> String {
    let suite_label = suite_display_name(&options.suite);
    let suite_subject = suite_subject(&options.suite);
    let latency = summarize(ranked);
    let latency_line = format!(
        "median per-case latency ratio **{}** (RedlineDB/SQLite, lower is better), p95 **{}**, worst **{}**, faster **{}/{}**; **{}** cases have a SQLite median under 3 ms (`below_resolution`)",
        format_ratio(latency.median_ratio),
        format_ratio(latency.p95_ratio),
        format_ratio(latency.worst_ratio),
        latency.faster,
        latency.cases,
        latency.below_resolution
    );
    let lane = evidence_versions.map_or("unrecorded (no official evidence)", |versions| {
        versions.lane.as_str()
    });
    let boundary_line = format!(
        "**Measurement boundary:** {MEASUREMENT_BOUNDARY_TEXT} (`{MEASUREMENT_BOUNDARY}`: process spawn, case execution and output collection; fixture writes untimed); lane={lane}; not a tuned benchmark.\n\n"
    );
    let mut block = String::new();
    block.push_str(&format!(
        "**{} coverage:** **{} / {}** {} passed in CI. Failed: **{}**. Skipped: **{}**. Updated {}.\n\n",
        suite_label,
        summary.passed_cases,
        summary.total_cases,
        suite_subject,
        summary.failed_cases,
        summary.skipped_cases,
        options.updated_date
    ));
    match options.suite.as_str() {
        "beyond_sqlite" => {
            block.push_str(&format!(
                "**{} progress:** coverage **{:.2}%**, promoted reference features **{}**, manifest backlog **{}**.\n\n",
                suite_label,
                if summary.total_cases == 0 {
                    0.0
                } else {
                    summary.passed_cases as f64 / summary.total_cases as f64 * 100.0
                },
                summary.passed_cases,
                summary.skipped_cases
            ));
        }
        "memory" => {
            let memory_status = memory_status_summary(raw_records);
            let memory_peaks = memory_peak_summary(raw_records)
                .unwrap_or_else(|| "no RSS samples were captured".to_owned());
            block.push_str(&format!(
                "**{suite_label} latency:** {latency_line}. RSS sampling: **{memory_status}**. {memory_peaks}.\n\n"
            ));
            block.push_str(&boundary_line);
        }
        _ => {
            block.push_str(&format!("**{suite_label} latency:** {latency_line}.\n\n"));
            block.push_str(&boundary_line);
        }
    }
    if let Some(evidence_versions) = evidence_versions {
        block.push_str(&format!(
            "**Benchmark metadata:** RedlineDB target version **{}**, SQLite reference version **{}**, redline-testing runner version **{}**.\n\n",
            evidence_versions.target_version,
            evidence_versions.sqlite_version,
            evidence_versions.runner_version
        ));
    }
    if let Some(plot) = &options.plot {
        block.push_str(&format!(
            "![{} latency ratio plot]({})\n\n",
            suite_label,
            plot.display()
        ));
    }
    if let Some(plot) = &options.performance_histogram_plot {
        block.push_str(&format!(
            "![{} performance distribution]({})\n\n",
            suite_label,
            plot.display()
        ));
    }
    let table_id = format!("{}-ranked-table", options.suite.replace('_', "-"));
    let table_summary = if options.suite == "beyond_sqlite" {
        "Full ranked feature table"
    } else {
        "Slowest 25 cases by latency ratio (every case is in ranked.csv)"
    };
    block.push_str(&format!(
        "<details id=\"{}\">\n<summary>{}</summary>\n\n",
        table_id, table_summary
    ));
    block.push_str("| Rank | Case | Priority | Profile | Category | SQLite median ns | RedlineDB median ns | Ratio | Gap |\n");
    block.push_str("| ---: | --- | --- | --- | --- | ---: | ---: | ---: | ---: |\n");
    for (index, row) in ranked.iter().take(25).enumerate() {
        block.push_str(&format!(
            "| {} | {} | {} | {} | {} | {} | {} | {} | {:+.2}% |\n",
            index + 1,
            row.name,
            row.priority,
            row.profile,
            row.category,
            row.sqlite_median_ns,
            row.redline_median_ns,
            format_ratio(row.latency_ratio),
            row.gap_pct
        ));
    }
    block.push_str("\n</details>\n");
    block
}

pub(crate) fn render_metrics_block(options: &ReportOptions) -> String {
    let suite_label = suite_display_name(&options.suite);
    let mut block = String::new();
    if let Some(plot) = &options.jankurai_score_plot {
        block.push_str(&format!("![{} score]({})\n\n", suite_label, plot.display()));
    }
    if let Some(plot) = &options.code_shape_plot {
        block.push_str(&format!(
            "![{} code shape]({})\n\n",
            suite_label,
            plot.display()
        ));
    }
    if let Some(plot) = &options.median_test_performance_plot {
        block.push_str(&format!(
            "![{} median test performance]({})\n\n",
            suite_label,
            plot.display()
        ));
    }
    if let Some(plot) = &options.ksloc_plot {
        block.push_str(&format!("![{} KSLOC]({})\n\n", suite_label, plot.display()));
    }
    if let Some(plot) = &options.jankurai_comparison_plot {
        block.push_str(&format!(
            "![{} Jankurai comparison]({})\n\n",
            suite_label,
            plot.display()
        ));
    }
    block
}

pub(crate) fn render_sqlite_badge(summary: &SummaryJson) -> String {
    let pct = if summary.total_cases == 0 {
        0.0
    } else {
        (summary.passed_cases as f64) * 100.0 / (summary.total_cases as f64)
    };
    let pct_text = if (pct - pct.round()).abs() < 0.001 {
        format!("{}", pct.round() as u64)
    } else {
        format!("{pct:.2}")
    };
    let color = if summary.failed_cases > 0 {
        "red"
    } else {
        "brightgreen"
    };
    format!(
        "  <a href=\"#sqlite-parity-status\"><img src=\"https://img.shields.io/badge/sqlite%20parity-{passed}%2F{total}%20({pct}%25)-{color}\" alt=\"sqlite parity {passed}/{total}\"></a>",
        passed = summary.passed_cases,
        total = summary.total_cases,
        pct = pct_text,
    )
}

pub(crate) fn replace_block_if_present(
    text: &str,
    begin: &str,
    end: &str,
    replacement: &str,
) -> String {
    match (text.find(begin), text.find(end)) {
        (Some(begin_index), Some(end_index)) if begin_index < end_index => {
            replace_block(text, begin, end, replacement)
        }
        _ => text.to_owned(),
    }
}

pub(crate) fn replace_block(text: &str, begin: &str, end: &str, replacement: &str) -> String {
    match (text.find(begin), text.find(end)) {
        (Some(begin_index), Some(end_index)) if begin_index < end_index => {
            let mut result = String::new();
            result.push_str(&text[..begin_index + begin.len()]);
            result.push('\n');
            result.push_str(replacement);
            result.push_str(&text[end_index..]);
            result
        }
        _ => format!("{text}\n{begin}\n{replacement}\n{end}\n"),
    }
}
