use std::collections::BTreeSet;

use anyhow::{Context, Result, anyhow, bail};

use super::case::Case;

const PINNED_MANIFEST: &str = include_str!("../../corpus/sqlite_parity/generated_manifest.json");

// EXTENDED_SHARDS is generated by build.rs from corpus/sqlite_parity/cases/*.json.
// Each entry is (file_stem, shard_contents_as_str).
include!(concat!(env!("OUT_DIR"), "/extended_shards.rs"));

/// Every corpus file compiled into this runner, as (name, contents): the
/// pinned manifest first, then each shard under corpus/sqlite_parity/cases in
/// file-name order, metadata shards included.
pub(super) fn corpus_files() -> impl Iterator<Item = (String, &'static str)> {
    std::iter::once(("generated_manifest.json".to_owned(), PINNED_MANIFEST)).chain(
        EXTENDED_SHARDS
            .iter()
            .map(|(stem, body)| (format!("cases/{stem}.json"), *body)),
    )
}

/// Cases from the pinned upstream manifest (IDs 1-1127). Read-only; this is
/// the migrated artifact from RedlineDB.
pub fn pinned_cases() -> Result<Vec<Case>> {
    serde_json::from_str(PINNED_MANIFEST)
        .context("parse sqlite parity pinned generated_manifest.json")
}

/// Cases authored directly in this repo (ID >= 10001). Loaded shard by shard
/// in alphabetical order so report enumeration is deterministic.
pub fn extended_cases() -> Result<Vec<Case>> {
    let mut all = Vec::new();
    for (stem, body) in EXTENDED_SHARDS {
        // Skip pure metadata shards (those starting with an underscore are
        // not case lists — see corpus/sqlite_parity/cases/_capabilities.json
        // for the data-driven capability table).
        if stem.starts_with('_') {
            continue;
        }
        let cases: Vec<Case> = serde_json::from_str(body)
            .with_context(|| format!("parse sqlite_parity/cases/{stem}.json"))?;
        all.extend(cases);
    }
    Ok(all)
}

/// Pinned + extended cases in canonical order (pinned first, then extended
/// by shard filename).
pub fn all_cases() -> Result<Vec<Case>> {
    let mut all = pinned_cases()?;
    all.extend(extended_cases()?);
    Ok(all)
}

pub fn selected_official_cases() -> Result<Vec<Case>> {
    let pinned_only = matches!(
        std::env::var("REDLINE_TESTING_PINNED_ONLY").ok().as_deref(),
        Some("1") | Some("true") | Some("TRUE")
    );
    let cases = if pinned_only {
        pinned_cases()?
    } else {
        all_cases()?
    };
    let cases = cases
        .into_iter()
        .filter(|case| case.status == "active" || case.status == "catalog_only")
        .collect::<Vec<_>>();
    if cases.is_empty() {
        bail!("sqlite parity selection matched zero cases");
    }
    Ok(cases)
}

/// `cases` narrowed to `case_ids`, or all of them when it is empty. An id
/// that names no case in `cases` is an error, so a typo never selects less
/// than was asked for.
pub(super) fn narrow_to_ids(cases: Vec<Case>, case_ids: &[String]) -> Result<Vec<Case>> {
    if case_ids.is_empty() {
        return Ok(cases);
    }
    let wanted = case_ids
        .iter()
        .map(|id| {
            id.trim()
                .parse::<usize>()
                .map_err(|_| anyhow!("--case-id {id:?} is not a case id"))
        })
        .collect::<Result<BTreeSet<_>>>()?;
    let selected = cases
        .into_iter()
        .filter(|case| wanted.contains(&case.id))
        .collect::<Vec<_>>();
    let found = selected.iter().map(|case| case.id).collect::<BTreeSet<_>>();
    let missing = wanted
        .difference(&found)
        .map(|id| format!("{id:05}"))
        .collect::<Vec<_>>();
    if !missing.is_empty() {
        bail!("--case-id names no selected case: {}", missing.join(", "));
    }
    Ok(selected)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::sqlite_parity::case::Priority;

    #[test]
    fn pinned_manifest_has_planned_size_and_ranges() {
        let cases = pinned_cases().expect("sqlite parity pinned manifest");
        assert_eq!(cases.len(), 1127);
        assert_eq!(cases[0].display_id(), "00001");
        assert_eq!(cases[1126].display_id(), "01127");
        assert_eq!(
            cases
                .iter()
                .filter(|case| case.priority == Priority::P0)
                .count(),
            130
        );
        assert_eq!(
            cases
                .iter()
                .filter(|case| case.priority == Priority::P1)
                .count(),
            579
        );
        assert_eq!(
            cases
                .iter()
                .filter(|case| case.priority == Priority::P2)
                .count(),
            370
        );
        assert_eq!(
            cases
                .iter()
                .filter(|case| case.priority == Priority::P3)
                .count(),
            24
        );
    }

    #[test]
    fn extended_ids_start_above_upstream_reserve() {
        // The pinned upstream range is 1..=1127, with 1128..=9999 reserved
        // for upstream growth. New cases authored in this repo land at >= 10001.
        let extended = extended_cases().expect("extended shards");
        for case in &extended {
            assert!(
                case.id >= 10001,
                "extended case id={} must be >= 10001 (reserve 1128..=9999 for upstream)",
                case.id
            );
        }
    }

    #[test]
    fn expected_failures_declare_an_error_fragment() {
        // A non-zero exit alone cannot tell the declared error from any other
        // failure (a missing table, a parse error, a crash), so every case
        // that expects one names text the failure must print.
        let violations = all_cases()
            .expect("sqlite parity corpus")
            .into_iter()
            .filter(|case| case.expected_exit != 0)
            .filter(|case| {
                !case
                    .expected_stderr_contains
                    .iter()
                    .chain(&case.expected_combined_contains)
                    .any(|needle| !needle.is_empty())
            })
            .map(|case| case.display_id())
            .collect::<Vec<_>>();
        assert!(
            violations.is_empty(),
            "cases with a non-zero expected_exit and no stderr or combined fragment: {violations:?}"
        );
    }

    #[test]
    fn uncompared_stdout_is_explained() {
        // A case that does not compare stdout says what in it is inherently
        // engine-specific (SQ-06 audit); a case that compares it says
        // nothing of the kind.
        let mut violations = Vec::new();
        for case in all_cases().expect("sqlite parity corpus") {
            let reason = case
                .stdout_uncompared_reason
                .as_deref()
                .filter(|reason| !reason.trim().is_empty());
            if case.compare_stdout == reason.is_some() {
                violations.push(case.display_id());
            }
        }
        assert!(
            violations.is_empty(),
            "compare_stdout must be false exactly when stdout_uncompared_reason is set: {violations:?}"
        );
    }

    #[test]
    fn combined_official_selection_is_ordered() {
        let cases = selected_official_cases().expect("official cases");
        assert!(!cases.is_empty());
        // Pinned cases come first, then extended; ids are strictly increasing.
        assert!(cases.windows(2).all(|pair| pair[0].id < pair[1].id));
        // P4 is present in the pinned set; it must survive selection.
        assert!(cases.iter().any(|case| case.priority == Priority::P4));
    }
}
