#!/usr/bin/env bash
# Public-tree hygiene for the open-source launch. Fails when a tracked path or a
# tracked file
#   - uses the old profane name of the chaos benchmark suite (now `chaos`), or
#   - carries a personal macOS home path (/Users/<name>/).
#
#   bash scripts/check-public-hygiene.sh          # the working tree's tracked files
#   bash scripts/check-public-hygiene.sh <commit>  # that commit's tree
#
# The exemptions are files this repository does not edit by hand. Each one
# still names the old suite path in an evidence list and loses it when it is
# regenerated (or, for CHANGELOG.md, when its owner edits the entry).
set -euo pipefail

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$root"
rev=${1:-}

# Split so this script does not match itself.
old_suite='dick[-_]head[-_]cho''as'
personal_home='/Users/[A-Za-z0-9._-]+/'
exempt=(
  # generated by `jankurai audit` (agent/generated-zones.toml)
  .jankurai/repo-score.json
  benchmark-results/sqlite-parity/latest/jankurai-score.txt
  # audit baselines; github-monorepo records main's sha256, so neither is edited
  .jankurai/baselines/main.repo-score.json
  .jankurai/baselines/github-monorepo.repo-score.json
  # written by the release integrator only
  CHANGELOG.md
)
pathspec=(.)
for path in "${exempt[@]}"; do
  pathspec+=(":(exclude)$path")
done

failures=0
if [[ -n $rev ]]; then
  paths=$(git ls-tree -r --name-only "$rev")
else
  paths=$(git ls-files)
fi
if bad_paths=$(grep -iE "$old_suite" <<<"$paths"); then
  printf 'public-hygiene: tracked paths use the old chaos suite name:\n%s\n' "$bad_paths" >&2
  failures=$((failures + 1))
fi
# git grep exits 1 when nothing matches.
if bad_files=$(git grep -I -l -i -E "$old_suite" ${rev:+"$rev"} -- "${pathspec[@]}"); then
  printf 'public-hygiene: tracked files name the old chaos suite:\n%s\n' "$bad_files" >&2
  failures=$((failures + 1))
fi
if bad_files=$(git grep -I -l -E "$personal_home" ${rev:+"$rev"} -- "${pathspec[@]}"); then
  printf 'public-hygiene: tracked files carry a personal home path:\n%s\n' "$bad_files" >&2
  failures=$((failures + 1))
fi

if ((failures)); then
  exit 1
fi
printf 'public-hygiene: ok\n'
