//! Rendering the version-history block from a checked summary: the table,
//! its footnote and the measurement line.

use std::fmt::Write as _;

use anyhow::Result;

use super::summary::{Delta, Spread, Summary, Verdict};

/// The block between the markers: the table and its footnote.
pub(super) fn render_block(summary: &Summary, link: &str) -> Result<String> {
    let mut out = String::new();
    writeln!(
        out,
        "<!-- Generated by `redline-testing version-history` from {link}/summary.json; do not edit by hand. -->"
    )?;
    if !summary.publishable {
        writeln!(
            out,
            "\n> **Not publishable:** {}.",
            summary.publication_blockers.join("; ")
        )?;
    }
    writeln!(out)?;
    let of = if summary.corpus.narrowed_by.is_some() {
        format!("of {} listed cases", summary.corpus.cases)
    } else {
        format!("of {}, today's corpus", summary.corpus.cases)
    };
    writeln!(
        out,
        "| Version | Commit | SQLite corpus passed ({of}) | Median latency ratio vs SQLite (lower is better) | p95 | Δ median vs previous |"
    )?;
    writeln!(out, "| --- | --- | ---: | ---: | ---: | --- |")?;
    for label in &summary.labels {
        let commit = label.source_commit.as_deref().map_or_else(
            || "not recorded".to_owned(),
            |commit| format!("`{}`", &commit[..commit.len().min(9)]),
        );
        let passed = if label.flaky_cases > 0 {
            format!("{} (+{} flaky)", label.passed_cases, label.flaky_cases)
        } else {
            label.passed_cases.to_string()
        };
        writeln!(
            out,
            "| {} | {commit} | {passed} | {} | {} | {} |",
            label.label,
            spread(&label.common.median),
            spread(&label.common.p95),
            delta(
                label.common.delta_vs_previous.as_ref(),
                summary.runs_per_label
            )
        )?;
    }
    writeln!(out)?;
    let runs = summary.runs_per_label;
    writeln!(
        out,
        "Each ratio compares RedlineDB with SQLite on the same case, and lower is better. The time is \
         per-case CLI process wall time (`{boundary}`): every sample starts a fresh `redlinedb` or \
         `sqlite3` shell, so process start-up is included. A case's ratio is RedlineDB's median over \
         SQLite's median across {reps} measured repetitions after {warmup} warmup. The table shows the \
         median and nearest-rank p95 of those ratios over the {common} cases every version passed in \
         every run (the common pass set). Each version ran {runs} time(s), interleaved with the others. \
         The figure is the median run, and the parentheses give the min–max across runs. A change is \
         shown only when the two versions' ranges do not overlap; otherwise it reads \"within noise\". \
         \"Passed\" counts the corpus cases a version passed in every run.",
        boundary = summary.protocol.measurement_boundary,
        reps = summary.protocol.repetitions,
        warmup = summary.protocol.warmup,
        common = summary.common_pass_set.cases,
    )?;
    writeln!(out)?;
    let pinned = summary.protocol.cpus.as_deref().map_or_else(
        || "unpinned".to_owned(),
        |cpus| format!("pinned to CPUs {cpus}"),
    );
    let durability = if summary.protocol.durability == "normal" {
        "`REDLINEDB_DEFAULT_DURABILITY=normal`".to_owned()
    } else {
        "each version's built-in default durability".to_owned()
    };
    let narrowed = if summary.corpus.narrowed_by.is_some() {
        " The corpus was narrowed by a case list."
    } else {
        ""
    };
    writeln!(
        out,
        "Measured {date} on {cpu} ({nproc} CPUs, {kernel}), {pinned}, {workers} worker(s), \
         `--order {order}`, temp roots on {fs}, {durability}. SQLite reference {reference} \
         (`{reference_sha}`); runner {runner}. {builds}{narrowed} Bundle: [`{link}`]({link}/).",
        date = summary
            .finished_at_utc
            .get(..10)
            .unwrap_or(&summary.finished_at_utc),
        cpu = summary.host.cpu_model,
        nproc = summary.host.nproc,
        kernel = summary.host.kernel,
        workers = summary.protocol.workers,
        order = summary.protocol.order,
        fs = summary.host.tmp_filesystem,
        reference = summary
            .reference
            .version
            .split_whitespace()
            .next()
            .unwrap_or("unknown"),
        reference_sha = &summary.reference.sha256[..summary.reference.sha256.len().min(12)],
        runner = summary.runner.version,
        builds = builds(summary),
    )?;
    Ok(out)
}

fn spread(spread: &Spread) -> String {
    if spread.per_run.len() < 2 {
        format!("{:.3}×", spread.value)
    } else {
        format!("{:.3}× ({:.3}–{:.3})", spread.value, spread.min, spread.max)
    }
}

fn delta(delta: Option<&Delta>, runs: usize) -> String {
    match delta {
        None => "—".to_owned(),
        Some(delta) => match delta.verdict {
            Verdict::WithinNoise => "within noise".to_owned(),
            Verdict::ExceedsNoise => format!("{:+.1}%", delta.median_change_pct),
            Verdict::Unassessed => format!("not assessed ({runs} run)"),
        },
    }
}

fn builds(summary: &Summary) -> String {
    let first = &summary.labels[0].build;
    let alike = summary.labels.iter().all(|label| {
        label.build.declared
            && label.build.profile.as_deref() == Some("release")
            && label.build.rustflags == first.rustflags
    });
    match (&first.rustflags, alike) {
        (Some(flags), true) => format!(
            "Every version was built with the release profile and RUSTFLAGS `{}`, without PGO.",
            if flags.is_empty() { "\"\"" } else { flags }
        ),
        _ => "The versions' builds differ or are undeclared; see the bundle.".to_owned(),
    }
}
