#!/usr/bin/env bash
# Prints the README.md of a release bench bundle (L-05) from the bundle's
# bundle.json, host.json, cases.json and build contracts. It describes how
# the bundle was measured and what its numbers do and do not mean.
# scripts/perf/release-bench.sh writes it; it is generated, never edited.
#
# Usage: scripts/perf/release-bench-readme.sh <bundle-dir> > <bundle-dir>/README.md

set -euo pipefail

dir="${1:?usage: release-bench-readme.sh <bundle-dir>}"
bundle_json="$dir/bundle.json"
host_json="$dir/host.json"
cases_json="$dir/cases.json"
for file in "$bundle_json" "$host_json" "$cases_json"; do
  [ -f "$file" ] || { printf 'release-bench-readme: missing %s\n' "$file" >&2; exit 2; }
done

field() { jq -r "$1" "$bundle_json"; }
first_contract="$dir/$(field '.labels[0].build_contract')"

bundle="$(field '.bundle')"
started="$(field '.started_at_utc')"
finished="$(field '.finished_at_utc')"
runs="$(field '.runs_per_label')"
cases="$(field '.cases.count')"
cpus="$(field '.protocol.cpus // "none"')"
durability="$(field '.protocol.durability')"
max_loadavg="$(field '.protocol.max_loadavg')"
command_line="$(field '.protocol.command')"
tmp_root="$(field '.protocol.tmp_root')"
narrowed="$(field '.cases.case_list != null')"
reference_version="$(jq -r '.reference.version' "$first_contract")"
reference_sha="$(jq -r '.reference.sha256' "$first_contract")"
runner_version="$(jq -r '.runner.version' "$first_contract")"
runner_sha="$(jq -r '.runner.sha256' "$first_contract")"
cpu_model="$(jq -r '.cpu_model' "$host_json")"
nproc_count="$(jq -r '.nproc' "$host_json")"
kernel="$(jq -r '.kernel' "$host_json")"
tmp_filesystem="$(jq -r '.tmp_filesystem' "$host_json")"
profiles="$(jq -r 'group_by(.profile) | map("\(length) \(.[0].profile)") | join(", ")' "$cases_json")"
memory_cases="$(jq '[.[] | select(.profile == "memory")] | length' "$cases_json")"
sequence="$(field '[.runs | sort_by(.sequence)[] | "\(.label) \(.run)"] | join(", ")')"

cat <<EOF
# Release bench bundle \`$bundle\`

Generated by \`scripts/perf/release-bench.sh\` from runs between $started and $finished (UTC).
Every file here is generated. Do not edit any of them by hand. To recompute \`summary.json\` from
the raw records, run \`perf_evidence summarize-bundle --bundle <this directory>\`; add \`--check\`
to verify it. \`redline-testing version-history --bundle <this directory>\` renders the README's
version table from \`summary.json\`.

## What was measured

| Label | Source | Binary SHA-256 | Build | Durability knob |
| --- | --- | --- | --- | --- |
EOF
jq -r '.labels[] | "| \(.label) | \(if .source_commit then "`\(.source_commit[0:12])` (\(.source_ref))" else "not recorded" end) | `\(.binary_sha256[0:16])…` | \(if .build_record then "build.json" else "undeclared" end) | \(if .durability_env then "yes" else "no (always Strict)" end) |"' "$bundle_json"
cat <<EOF

Each label ran $runs time(s), interleaved with the other labels, and the first label rotates
each round. The run order was: $sequence.

- **Runner command:** \`$command_line\`
- **SQLite reference:** $reference_version (sha256 \`$reference_sha\`), the same binary for every
  label.
- **Runner:** $runner_version (sha256 \`$runner_sha\`).
- **Host:** $cpu_model, $nproc_count CPUs, $kernel. Runs were pinned to CPUs \`$cpus\`
  (\`none\` means unpinned), one case at a time (\`--workers 1\`).
- **Load:** a run was accepted only when the 1-minute load average before and after it was at
  most $max_loadavg. \`host.json\` records each run's load averages, the CI runner services that
  were active and any CI runner jobs in progress.
EOF
if [ "$narrowed" = true ]; then
  cat <<EOF
- **Cases:** $cases, narrowed by \`case-list.txt\`. This is a diagnostic bundle: its summary is
  not publishable.
EOF
else
  cat <<EOF
- **Cases:** the whole \`sqlite_parity\` corpus of the runner above, $cases cases.
EOF
fi
cat <<EOF

## Disclosures

- **Measurement boundary (\`cli_case_wall_time\`).** Each sample is the wall time of one shell
  process per engine. The runner spawns \`sqlite3\` or \`redlinedb\`, feeds the case's script on
  stdin, and waits for its output and exit. Writing fixture files is not timed. A ratio
  therefore includes process start-up, shell parsing and teardown. It is not in-process query
  latency.
EOF
if [ "$durability" = normal ]; then
  cat <<EOF
- **Durability.** Every run exported \`REDLINEDB_DEFAULT_DURABILITY=normal\` and
  \`REDLINEDB_QUIET_DURABILITY=1\`, as the official lane does. RedlineDB therefore committed
  with Normal durability instead of its Strict default. A binary without the knob (v4.0.9 and
  older, marked "no" above) ignores it and ran Strict. The summary marks such a bundle not
  publishable, because its labels did not run the same way.
EOF
else
  cat <<EOF
- **Durability.** No durability override was exported. Each binary ran its built-in default
  (Strict for every RedlineDB release so far).
EOF
fi
if [ "$tmp_filesystem" = tmpfs ]; then
  cat <<EOF
- **tmpfs.** Each run's temp root, which holds the case databases and fixtures, was a fresh
  directory on tmpfs (\`$tmp_root\`), removed after the run. Neither engine paid for disk I/O,
  and an fsync on tmpfs touches no device.
EOF
else
  cat <<EOF
- **Temp root not on tmpfs.** Each run's temp root, which holds the case databases and
  fixtures, was a fresh directory (\`$tmp_root\`) on $tmp_filesystem, not tmpfs, so disk I/O is
  part of the timings. The summary marks the bundle not publishable.
EOF
fi
cat <<EOF
- **\`:memory:\`.** $memory_cases of the $cases cases use the \`memory\` profile, whose databases are
  \`:memory:\` ($profiles). Those cases never touch a database file.
- **Order and warmup.** \`--order alternate\`: SQLite runs first on even sample indexes, which
  are the warmup and measured:2, and RedlineDB runs first on odd ones. Each case has 1 warmup,
  which is not counted, and 3 measured repetitions.
- **Statistics.** Each case's ratio is RedlineDB's median over SQLite's median of its 3 measured
  repetitions; lower is better. A run's figure is the median, and the nearest-rank p95, of those
  ratios over the common pass set, which is the cases every label passed in every run. A label's
  figure is the median of its $runs run figures, and its range is their min-max. A change against
  the previous label is claimed only when the two ranges do not overlap. The pass count on the
  corpus is reported separately, as cases passed in every run; a case that passed in only some
  runs is counted as flaky.
- **Medium cohort.** \`cohorts/medium-set.txt\` is the historical 294-case list
  (\`bench/perf/cases/medium-set.txt\`; see \`bench/perf/cases/README.md\`). It was chosen partly
  for being slow in one 2026-05 run, so it favors later versions. It is sliced from the same
  runs as a secondary view only.

## Files

- \`bundle.json\`: the protocol, the labels and the runs, in order.
- \`host.json\`: host facts, and each run's load averages and runner exit status.
- \`cases.json\`: the runner's corpus listing (id, name, category, priority, profile).
- \`<label>/build-contract.json\`: the binary, the reference and the runner by SHA-256, the
  reference's compile options and the declared build. \`<label>/build.json\` is
  \`scripts/perf/build-version.sh\`'s record of the build, when that script built the binary.
- \`<label>/run-<k>/\`: the runner's \`raw.jsonl\` and its completion marker, the runner's own
  evidence (\`manifest.json\`, \`provenance.json\`, \`summary.json\`, \`ranked.csv\`), its log and
  \`validation.txt\`.
- \`summary.json\`: \`perf_evidence summarize-bundle\` output. It lists why the bundle is not
  publishable, if it is not.
EOF
